// Stub file for Vercel builds
// This file is normally generated by Wrangler (Cloudflare)
// For Vercel deployments, we provide an empty stub

interface Env {
  // Empty interface for Vercel builds
  // In Cloudflare, this would contain bindings like DB, R2_BUCKET, etc.
}

export type { Env };

